/* Builds data/films.js from TMDB. Run this once; commit the result.
 *
 *   TMDB_KEY=your_key node scripts/build-catalog.mjs
 *
 * Get a free key at themoviedb.org/settings/api (v3 auth, the short key).
 * Options:
 *   PAGES=30   how many discover pages to pull (20 films each)
 *   MIN_VOTES=300  floor for vote_count — lower pulls in more obscure films
 */

import { writeFile } from "node:fs/promises";

const KEY = process.env.TMDB_KEY;
const PAGES = Number(process.env.PAGES || 30);
const MIN_VOTES = Number(process.env.MIN_VOTES || 300);
const BASE = "https://api.themoviedb.org/3";

if (!KEY) {
  console.error("Set TMDB_KEY first:  TMDB_KEY=xxxx node scripts/build-catalog.mjs");
  process.exit(1);
}

const get = async path => {
  const sep = path.includes("?") ? "&" : "?";
  const res = await fetch(`${BASE}${path}${sep}api_key=${KEY}`);
  if (!res.ok) throw new Error(`${res.status} on ${path}`);
  return res.json();
};

/* 1. Candidates. Sorted by vote_count so the floor is what controls obscurity. */
const ids = new Set();
for (let page = 1; page <= PAGES; page++) {
  const data = await get(
    `/discover/movie?sort_by=vote_count.desc&vote_count.gte=${MIN_VOTES}` +
    `&include_adult=false&language=en-US&page=${page}`
  );
  data.results.forEach(m => ids.add(m.id));
  process.stdout.write(`\rdiscover: ${ids.size} candidates`);
  if (page >= data.total_pages) break;
}
console.log("");

/* 2. Details — runtime and certification only come from here. */
const films = [];
let done = 0;
for (const id of ids) {
  try {
    const m = await get(`/movie/${id}?append_to_response=release_dates&language=en-US`);
    if (!m.runtime || !m.genres.length || !m.overview) continue;

    const us = (m.release_dates?.results || []).find(r => r.iso_3166_1 === "US");
    const cert = us?.release_dates?.map(r => r.certification).find(Boolean) || "NR";

    films.push({
      title: m.title,
      year: Number((m.release_date || "").slice(0, 4)) || null,
      runtime: m.runtime,
      genres: m.genres.map(g => g.id),
      rating: Math.round(m.vote_average * 10) / 10,
      votes: m.vote_count,
      cert,
      poster: m.poster_path || null,
      overview: m.overview.length > 200 ? m.overview.slice(0, 197).trimEnd() + "…" : m.overview
    });
  } catch (err) {
    console.warn(`\nskipped ${id}: ${err.message}`);
  }
  done++;
  if (done % 25 === 0) process.stdout.write(`\rdetails: ${done}/${ids.size}`);
}
console.log("");

films.sort((a, b) => b.votes - a.votes);

const header =
  "/* Generated by scripts/build-catalog.mjs from TMDB. Do not hand-edit.\n" +
  `   ${films.length} films · vote_count >= ${MIN_VOTES}\n` +
  "   Poster URLs: https://image.tmdb.org/t/p/w342 + poster */\n";

await writeFile("data/films.js", header + "window.FILMS = " + JSON.stringify(films, null, 0) + ";\n");

const discovery = films.filter(f => f.votes < 4000 && f.rating >= 7).length;
console.log(`wrote data/films.js — ${films.length} films, ${discovery} of them Discovery-Mode candidates`);
