/* Builds data/films.js from TMDB. Run this once; commit the result.
 *
 *   TMDB_KEY=your_key node scripts/build-catalog.mjs
 *
 * Get a free key at themoviedb.org/settings/api (v3 auth, the short key).
 * Two passes, because one sorted query cannot give you both:
 *   1. MAINSTREAM — the films most people have heard of, as an anchor.
 *   2. GEMS       — well-rated but under-seen films. This is Discovery Mode;
 *                   without this pass every result is a blockbuster.
 *
 * Options:
 *   POPULAR_PAGES=15  pages of mainstream films (20 each)
 *   GEM_PAGES=15      pages of under-seen films (20 each)
 *   MIN_VOTES=1000    quality floor for the mainstream pass
 *   GEM_MIN=300       quality floor for gems — raise it for safer picks
 *   GEM_MAX=4000      obscurity ceiling; must match isDiscovery() in match.js
 *   GEM_RATING=7      minimum average rating for a gem
 */

import { writeFile } from "node:fs/promises";

const KEY = process.env.TMDB_KEY;
const POPULAR_PAGES = Number(process.env.POPULAR_PAGES || 15);
const GEM_PAGES = Number(process.env.GEM_PAGES || 15);
const MIN_VOTES = Number(process.env.MIN_VOTES || 1000);
const GEM_MIN = Number(process.env.GEM_MIN || 300);
const GEM_MAX = Number(process.env.GEM_MAX || 4000);
const GEM_RATING = Number(process.env.GEM_RATING || 7);
const BASE = "https://api.themoviedb.org/3";

if (!KEY) {
  console.error("Set TMDB_KEY first:  TMDB_KEY=xxxx node scripts/build-catalog.mjs");
  process.exit(1);
}

const sleep = ms => new Promise(r => setTimeout(r, ms));

/* TMDB rate-limits in bursts. Back off and retry rather than losing films. */
const get = async (path, attempt = 0) => {
  const sep = path.includes("?") ? "&" : "?";
  const res = await fetch(`${BASE}${path}${sep}api_key=${KEY}`);

  if (res.status === 429 && attempt < 5) {
    const wait = Number(res.headers.get("retry-after") || 2) * 1000;
    await sleep(wait);
    return get(path, attempt + 1);
  }
  if (res.status === 401) {
    console.error("\nTMDB rejected the key. Check TMDB_KEY is the v3 API key.");
    process.exit(1);
  }
  if (!res.ok) throw new Error(`${res.status} on ${path}`);
  return res.json();
};

/* 1. Candidates, in two passes. */
const ids = new Set();

const collect = async (label, pages, query) => {
  const before = ids.size;
  for (let page = 1; page <= pages; page++) {
    const data = await get(`/discover/movie?${query}&include_adult=false&language=en-US&page=${page}`);
    data.results.forEach(m => ids.add(m.id));
    process.stdout.write(`\r${label}: ${ids.size - before} films`);
    if (page >= data.total_pages) break;
  }
  console.log("");
  return ids.size - before;
};

await collect("mainstream", POPULAR_PAGES,
  `sort_by=vote_count.desc&vote_count.gte=${MIN_VOTES}`);

/* Sorted descending within the obscure band: the best-known of the little-known,
   which is what a good recommendation feels like — not the truly unheard-of. */
const gems = await collect("gems", GEM_PAGES,
  `sort_by=vote_count.desc&vote_count.gte=${GEM_MIN}` +
  `&vote_count.lte=${GEM_MAX}&vote_average.gte=${GEM_RATING}`);

if (!gems) console.warn("warning: the gem pass returned nothing — Discovery Mode will be empty");

/* 2. Details — runtime and certification only come from here. */
const films = [];
let done = 0;
for (const id of ids) {
  try {
    const m = await get(`/movie/${id}?append_to_response=release_dates&language=en-US`);
    if (!m.runtime || !m.genres.length || !m.overview) continue;

    const us = (m.release_dates?.results || []).find(r => r.iso_3166_1 === "US");
    const cert = us?.release_dates?.map(r => r.certification).find(Boolean) || "NR";

    films.push({
      /* Stable across catalogue refreshes, unlike the title — this is what
         "already seen" marks are keyed on. */
      id: m.id,
      title: m.title,
      year: Number((m.release_date || "").slice(0, 4)) || null,
      runtime: m.runtime,
      genres: m.genres.map(g => g.id),
      rating: Math.round(m.vote_average * 10) / 10,
      votes: m.vote_count,
      cert,
      poster: m.poster_path || null,
      overview: m.overview.length > 200 ? m.overview.slice(0, 197).trimEnd() + "…" : m.overview
    });
  } catch (err) {
    console.warn(`\nskipped ${id}: ${err.message}`);
  }
  done++;
  if (done % 25 === 0) process.stdout.write(`\rdetails: ${done}/${ids.size}`);
}
console.log("");

films.sort((a, b) => b.votes - a.votes);

const header =
  "/* Generated by scripts/build-catalog.mjs from TMDB. Do not hand-edit.\n" +
  `   ${films.length} films · mainstream >= ${MIN_VOTES} votes · gems ${GEM_MIN}-${GEM_MAX} votes\n` +
  "   Poster URLs: https://image.tmdb.org/t/p/w342 + poster */\n";

await writeFile("data/films.js", header + "window.FILMS = " + JSON.stringify(films, null, 0) + ";\n");

const discovery = films.filter(f => f.votes < GEM_MAX && f.rating >= 7).length;
console.log(`wrote data/films.js — ${films.length} films, ${discovery} of them Discovery-Mode candidates`);
if (!discovery) {
  console.error("No Discovery-Mode films: every result is a blockbuster. Check the gem pass.");
  process.exit(1);
}
